### ISSUE TITLE
Add Base Sepolia testnet

### ISSUE THREAD

**Issue by actuallymentor** [RabbyHub/RabbyDesktop#629]
Hello team!

Could you please add the Base Sepolia testnet? [These are the official base docs](https://docs.base.org/using-base/) from which the testnet rpc data is:

```
Name	Sepolia
Network Name	Base Sepolia
RPC Endpoint	https://sepolia.base.org/
Chain ID	84532
Currency Symbol	ETH
Block Explorer	https://sepolia-explorer.base.org/
```

If you are overwhelmed and would appreciate a PR please point me in the right direction and I'll make one.

**Comment by vvvvvv1vvvvvv** [comment]
Rabby Desktop support custom network now, so you can add it by yourself
