### ISSUE TITLE
Custom RPC!

### ISSUE THREAD

**Issue by mickaphd** [RabbyHub/RabbyDesktop#651]
I'm surprised to see that we can't add custom RPCs to Rabby Desktop, and when I say custom I really mean custom, not the ones imposed in your list. 
Can you at least add Avocado's RPC (Instadapp)?

**Comment by richardo2016x** [comment]
Hi, Thanks for you support!

At the recent releases, of course you can add custom RPCs like below:

![image](https://github.com/user-attachments/assets/d5e3c61b-00a2-4460-8fda-4457d95f4600)
