### ISSUE TITLE
Update Balance Data button does not work.

### ISSUE THREAD

**Issue by poseidonPLS** [RabbyHub/RabbyDesktop#657]
The button that refreshes balances does not work anymore.

![Screenshot 2024-09-04 at 1 01 16 PM](https://github.com/user-attachments/assets/3d3dcc82-2dfa-4c86-aa9c-f7d8ef947119)

**Comment by richardo2016x** [comment]
Please upgrade to latest version and retry, it should be resolved in 0.38.6
